FROM mcr.microsoft.com/mssql/server

WORKDIR /usr/src/app

COPY . /usr/src/app

ENV SA_PASSWORD password123!
ENV ACCEPT_EULA Y

EXPOSE 1433

RUN /opt/mssql/bin/sqlservr --accept-eula & (sleep 15 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'password123!' -i /usr/src/app/create-database.sql)