FROM mcr.microsoft.com/mssql/server

WORKDIR /usr/src/app

COPY . /usr/src/app

ENV SA_PASSWORD pass
ENV ACCEPT_EULA Y

EXPOSE 1433

RUN ( /opt/mssql/bin/sqlserver --accept-eula &) | grep -q "Service has starte" \
     && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'pass' -i /usr/src/app/create-database.sql \
     && pkill sqlserver)